# Build settings
markdown: kramdown
encoding: utf-8

excerpt_separator: <!-- more -->
google_analytics: UA-20500320-1

# jekyll-seo-tag
title: matea2 blog
description: matea2のブログ
url: https://matea2.github.io
author: matea2
lang: ja

# minima
theme: minima
minima:
  date_format: "%F"
  social_links:
    twitter: matea2
    github: matea2


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# jekyll-paginate
paginate: 10
paginate_path: /blog/page:num/
